### ISSUE TITLE
If I want to know the coordinates of  Bounding-box (four points), what should I do

### ISSUE THREAD

**Issue by HotCoCoC** [Xilinx/QNN-MO-PYNQ#50]
This is what the author wrote here:(in the project of tiny-yolo-image.ipynb)

 
6. Draw detection boxes using Darknet
The image postprocessing (drawing the bounding boxes) is performed in darknet using python bindings.

Then he used this function (lib.draw_detection_python()) to draw the bounding-box,if I want to know the location of the box. What should I do?

**Comment by giuliogamba** [comment]
As you see in the notebook [example](https://github.com/Xilinx/QNN-MO-PYNQ/blob/master/notebooks/tiny-yolo-image.ipynb), the notebook is calling the `draw_detection_python` function from darknet, which is defined [here](https://github.com/giuliogamba/darknet/blob/master/examples/detector.c). 
If you want to get more information, you can modify the call to return the variable boxes, probs etc in darknet, recompile the darknet shared object in order to get those info in python. 
Hope this helps.

_Originally posted by @giuliogamba in https://github.com/Xilinx/QNN-MO-PYNQ/issues/26#issuecomment-455185719_
